In [1]:
import torch

In [3]:
x = torch.tensor(2.0,requires_grad = True)

In [4]:
y = 2*x**4  + x**3+ 3*x**2 + 5*x + 1 

In [5]:
print(y)

tensor(63., grad_fn=<AddBackward0>)


In [6]:
type(y)

torch.Tensor

In [8]:
y.backward()

In [9]:
x.grad

tensor(93.)

In [10]:
x = torch.tensor([[1.0,2.0,3.0],[3.0,2.0,1.0]],requires_grad = True)

In [11]:
x

tensor([[1., 2., 3.],
        [3., 2., 1.]], requires_grad=True)

In [12]:
y = 3*x + 2

In [13]:
y

tensor([[ 5.,  8., 11.],
        [11.,  8.,  5.]], grad_fn=<AddBackward0>)

In [14]:
z = 2*y**2

In [15]:
z

tensor([[ 50., 128., 242.],
        [242., 128.,  50.]], grad_fn=<MulBackward0>)

In [16]:
out = z.mean()

In [17]:
out

tensor(140., grad_fn=<MeanBackward0>)

In [19]:
out.backward()

In [20]:
x.grad

tensor([[10., 16., 22.],
        [22., 16., 10.]])