In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

import torch
import torch.nn as nn


In [2]:
path = 'PYTORCH_NOTEBOOKS/Data'

In [3]:
df = pd.read_csv(path + "/NYCTaxiFares.csv")

In [4]:

df.head()

pickup_datetime  fare_amount  fare_class  pickup_longitude  \
0  2010-04-19 08:17:56 UTC          6.5           0        -73.992365   
1  2010-04-17 15:43:53 UTC          6.9           0        -73.990078   
2  2010-04-17 11:23:26 UTC         10.1           1        -73.994149   
3  2010-04-11 21:25:03 UTC          8.9           0        -73.990485   
4  2010-04-17 02:19:01 UTC         19.7           1        -73.990976   

   pickup_latitude  dropoff_longitude  dropoff_latitude  passenger_count  
0        40.730521         -73.975499         40.744746                1  
1        40.740558         -73.974232         40.744114                1  
2        40.751118         -73.960064         40.766235                2  
3        40.756422         -73.971205         40.748192                1  
4        40.734202         -73.905956         40.743115                1

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120000 entries, 0 to 119999
Data columns (total 8 columns):
pickup_datetime      120000 non-null object
fare_amount          120000 non-null float64
fare_class           120000 non-null int64
pickup_longitude     120000 non-null float64
pickup_latitude      120000 non-null float64
dropoff_longitude    120000 non-null float64
dropoff_latitude     120000 non-null float64
passenger_count      120000 non-null int64
dtypes: float64(5), int64(2), object(1)
memory usage: 7.3+ MB


In [6]:
def haversine_distance(df, lat1, long1, lat2, long2):
    """
    Calculates the haversine distance between 2 sets of GPS coordinates in df
    """
    r = 6371  # average radius of Earth in kilometers
       
    phi1 = np.radians(df[lat1])
    phi2 = np.radians(df[lat2])
    
    delta_phi = np.radians(df[lat2]-df[lat1])
    delta_lambda = np.radians(df[long2]-df[long1])
     
    a = np.sin(delta_phi/2)**2 + np.cos(phi1) * np.cos(phi2) * np.sin(delta_lambda/2)**2
    c = 2 * np.arctan2(np.sqrt(a), np.sqrt(1-a))
    d = (r * c) # in kilometers

    return d

In [7]:
df.columns

Index(['pickup_datetime', 'fare_amount', 'fare_class', 'pickup_longitude',
       'pickup_latitude', 'dropoff_longitude', 'dropoff_latitude',
       'passenger_count'],
      dtype='object')

In [8]:
df['dist'] = haversine_distance(df,'pickup_latitude','pickup_longitude','dropoff_latitude','dropoff_longitude')

In [9]:
df.head()

pickup_datetime  fare_amount  fare_class  pickup_longitude  \
0  2010-04-19 08:17:56 UTC          6.5           0        -73.992365   
1  2010-04-17 15:43:53 UTC          6.9           0        -73.990078   
2  2010-04-17 11:23:26 UTC         10.1           1        -73.994149   
3  2010-04-11 21:25:03 UTC          8.9           0        -73.990485   
4  2010-04-17 02:19:01 UTC         19.7           1        -73.990976   

   pickup_latitude  dropoff_longitude  dropoff_latitude  passenger_count  \
0        40.730521         -73.975499         40.744746                1   
1        40.740558         -73.974232         40.744114                1   
2        40.751118         -73.960064         40.766235                2   
3        40.756422         -73.971205         40.748192                1   
4        40.734202         -73.905956         40.743115                1   

       dist  
0  2.126312  
1  1.392307  
2  3.326763  
3  1.864129  
4  7.231321

In [10]:
df['pickup_datetime']=  pd.to_datetime(df['pickup_datetime'])

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120000 entries, 0 to 119999
Data columns (total 9 columns):
pickup_datetime      120000 non-null datetime64[ns, UTC]
fare_amount          120000 non-null float64
fare_class           120000 non-null int64
pickup_longitude     120000 non-null float64
pickup_latitude      120000 non-null float64
dropoff_longitude    120000 non-null float64
dropoff_latitude     120000 non-null float64
passenger_count      120000 non-null int64
dist                 120000 non-null float64
dtypes: datetime64[ns, UTC](1), float64(6), int64(2)
memory usage: 8.2 MB


In [12]:
df['EDT'] = df['pickup_datetime'] - pd.Timedelta(hours = 4)

In [13]:
df.head()

pickup_datetime  fare_amount  fare_class  pickup_longitude  \
0 2010-04-19 08:17:56+00:00          6.5           0        -73.992365   
1 2010-04-17 15:43:53+00:00          6.9           0        -73.990078   
2 2010-04-17 11:23:26+00:00         10.1           1        -73.994149   
3 2010-04-11 21:25:03+00:00          8.9           0        -73.990485   
4 2010-04-17 02:19:01+00:00         19.7           1        -73.990976   

   pickup_latitude  dropoff_longitude  dropoff_latitude  passenger_count  \
0        40.730521         -73.975499         40.744746                1   
1        40.740558         -73.974232         40.744114                1   
2        40.751118         -73.960064         40.766235                2   
3        40.756422         -73.971205         40.748192                1   
4        40.734202         -73.905956         40.743115                1   

       dist                       EDT  
0  2.126312 2010-04-19 04:17:56+00:00  
1  1.392307 2010-04-17 11:43:53+00:00  
2  3.326763 2010-04-17 07:23:26+00:00  
3  1.864129 2010-04-11 17:25:03+00:00  
4  7.231321 2010-04-16 22:19:01+00:00

In [14]:
df['hour'] = df['EDT'].dt.hour

In [15]:
df['hour'].head()

0     4
1    11
2     7
3    17
4    22
Name: hour, dtype: int64

In [16]:
df['AMorPM'] = np.where(df['hour'] < 12 ,'am','pm')

In [17]:
df.head()

pickup_datetime  fare_amount  fare_class  pickup_longitude  \
0 2010-04-19 08:17:56+00:00          6.5           0        -73.992365   
1 2010-04-17 15:43:53+00:00          6.9           0        -73.990078   
2 2010-04-17 11:23:26+00:00         10.1           1        -73.994149   
3 2010-04-11 21:25:03+00:00          8.9           0        -73.990485   
4 2010-04-17 02:19:01+00:00         19.7           1        -73.990976   

   pickup_latitude  dropoff_longitude  dropoff_latitude  passenger_count  \
0        40.730521         -73.975499         40.744746                1   
1        40.740558         -73.974232         40.744114                1   
2        40.751118         -73.960064         40.766235                2   
3        40.756422         -73.971205         40.748192                1   
4        40.734202         -73.905956         40.743115                1   

       dist                       EDT  hour AMorPM  
0  2.126312 2010-04-19 04:17:56+00:00     4     am  
1  1.392307 2010-04-17 11:43:53+00:00    11     am  
2  3.326763 2010-04-17 07:23:26+00:00     7     am  
3  1.864129 2010-04-11 17:25:03+00:00    17     pm  
4  7.231321 2010-04-16 22:19:01+00:00    22     pm

In [18]:
df['weekdays'] = df['EDT'].dt.strftime('%a')

In [19]:
df.head()

pickup_datetime  fare_amount  fare_class  pickup_longitude  \
0 2010-04-19 08:17:56+00:00          6.5           0        -73.992365   
1 2010-04-17 15:43:53+00:00          6.9           0        -73.990078   
2 2010-04-17 11:23:26+00:00         10.1           1        -73.994149   
3 2010-04-11 21:25:03+00:00          8.9           0        -73.990485   
4 2010-04-17 02:19:01+00:00         19.7           1        -73.990976   

   pickup_latitude  dropoff_longitude  dropoff_latitude  passenger_count  \
0        40.730521         -73.975499         40.744746                1   
1        40.740558         -73.974232         40.744114                1   
2        40.751118         -73.960064         40.766235                2   
3        40.756422         -73.971205         40.748192                1   
4        40.734202         -73.905956         40.743115                1   

       dist                       EDT  hour AMorPM weekdays  
0  2.126312 2010-04-19 04:17:56+00:00     4     am      Mon  
1  1.392307 2010-04-17 11:43:53+00:00    11     am      Sat  
2  3.326763 2010-04-17 07:23:26+00:00     7     am      Sat  
3  1.864129 2010-04-11 17:25:03+00:00    17     pm      Sun  
4  7.231321 2010-04-16 22:19:01+00:00    22     pm      Fri

In [20]:
df.columns

Index(['pickup_datetime', 'fare_amount', 'fare_class', 'pickup_longitude',
       'pickup_latitude', 'dropoff_longitude', 'dropoff_latitude',
       'passenger_count', 'dist', 'EDT', 'hour', 'AMorPM', 'weekdays'],
      dtype='object')

In [21]:
cat_cols = ['hour', 'AMorPM', 'weekdays']

In [29]:
cont_cols = ['pickup_latitude', 'pickup_longitude', 'dropoff_latitude', 'dropoff_longitude', 'passenger_count', 'dist']


In [30]:
y_val = ['fare_amount']

In [31]:
for col in cat_cols:
    df[col] = df[col].astype('category')

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120000 entries, 0 to 119999
Data columns (total 13 columns):
pickup_datetime      120000 non-null datetime64[ns, UTC]
fare_amount          120000 non-null float64
fare_class           120000 non-null int64
pickup_longitude     120000 non-null float64
pickup_latitude      120000 non-null float64
dropoff_longitude    120000 non-null float64
dropoff_latitude     120000 non-null float64
passenger_count      120000 non-null int64
dist                 120000 non-null float64
EDT                  120000 non-null datetime64[ns, UTC]
hour                 120000 non-null category
AMorPM               120000 non-null category
weekdays             120000 non-null category
dtypes: category(3), datetime64[ns, UTC](2), float64(6), int64(2)
memory usage: 9.5 MB


In [33]:
hr = df['hour'].cat.codes.values
wkdy = df['weekdays'].cat.codes.values
ampm = df['AMorPM'].cat.codes.values

In [40]:
cats = np.stack([hr,ampm,wkdy],1)

In [41]:
cont = np.stack([df[col].values for col in cont_cols],1)

In [42]:
cont

array([[ 40.730521  , -73.992365  ,  40.744746  , -73.975499  ,
          1.        ,   2.12631159],
       [ 40.740558  , -73.990078  ,  40.744114  , -73.974232  ,
          1.        ,   1.39230687],
       [ 40.751118  , -73.994149  ,  40.766235  , -73.960064  ,
          2.        ,   3.32676344],
       ...,
       [ 40.749772  , -73.988574  ,  40.707799  , -74.011541  ,
          3.        ,   5.05252282],
       [ 40.724529  , -74.004449  ,  40.730765  , -73.992697  ,
          1.        ,   1.20892296],
       [ 40.77192   , -73.955415  ,  40.763015  , -73.967623  ,
          3.        ,   1.42739869]])

In [43]:
cats = torch.tensor(cats,dtype = torch.int64)

In [44]:
cats

tensor([[ 4,  0,  1],
        [11,  0,  2],
        [ 7,  0,  2],
        ...,
        [14,  1,  3],
        [ 4,  0,  5],
        [12,  1,  2]])

In [45]:
cont = torch.tensor(cont,dtype = torch.float)

In [46]:
cont

tensor([[ 40.7305, -73.9924,  40.7447, -73.9755,   1.0000,   2.1263],
        [ 40.7406, -73.9901,  40.7441, -73.9742,   1.0000,   1.3923],
        [ 40.7511, -73.9941,  40.7662, -73.9601,   2.0000,   3.3268],
        ...,
        [ 40.7498, -73.9886,  40.7078, -74.0115,   3.0000,   5.0525],
        [ 40.7245, -74.0044,  40.7308, -73.9927,   1.0000,   1.2089],
        [ 40.7719, -73.9554,  40.7630, -73.9676,   3.0000,   1.4274]])

In [47]:
y = torch.tensor(df[y_val].values,dtype = torch.float)

In [48]:
y

tensor([[ 6.5000],
        [ 6.9000],
        [10.1000],
        ...,
        [12.5000],
        [ 4.9000],
        [ 5.3000]])

In [49]:
cat_sz = [len(df[col].cat.categories) for col in cat_cols]

In [50]:
cat_sz

[24, 2, 7]

In [51]:
emb_sz = [(size,min(50,(size+1)//2)) for size in cat_sz]

In [52]:
emb_sz

[(24, 12), (2, 1), (7, 4)]

In [53]:
class TabularModel2(nn.Module):
    
    def __init__(self,emb_sz,n_cont,out_sz,layers, p=0.5):
        super().__init__()
        self.embeds = nn.ModuleList([nn.Embedding(ni,nf) for ni,nf in emb_sz])
        self.emb_drop = nn.Dropout(p)
        self.bn_cont = nn.BatchNorm1d(n_cont)
        
        layerlist = []
        
        n_emb = sum((nf for ni,nf in emb_sz))
        n_in = n_cont + n_emb
        for i in layers:
            layerlist.append(nn.Linear(n_in,i))
            layerlist.append(nn.ReLU(inplace=True))
            layerlist.append(nn.BatchNorm1d(i))
            layerlist.append(nn.Dropout(p))
            n_in = i
        layerlist.append(nn.Linear(layers[-1],out_sz))
        self.layers = nn.Sequential(*layerlist)
        
    def forward(self,x_cat,x_cont):
        embedingz = []
        for i,e in enumerate(self.embeds):
            embedingz.append(e(x_cat[:,i]))
        x = torch.cat(embedingz,1)
        x  = self.emb_drop(x)
        
        x_cont = self.bn_cont(x_cont)
        x = torch.cat([x,x_cont],1)
        x = self.layers(x)
        return x

In [55]:
model = TabularModel2(emb_sz,cont.shape[1],1,[200,100],p = 0.4)

In [56]:
model

TabularModel2(
  (embeds): ModuleList(
    (0): Embedding(24, 12)
    (1): Embedding(2, 1)
    (2): Embedding(7, 4)
  )
  (emb_drop): Dropout(p=0.4, inplace=False)
  (bn_cont): BatchNorm1d(6, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (layers): Sequential(
    (0): Linear(in_features=23, out_features=200, bias=True)
    (1): ReLU(inplace=True)
    (2): BatchNorm1d(200, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (3): Dropout(p=0.4, inplace=False)
    (4): Linear(in_features=200, out_features=100, bias=True)
    (5): ReLU(inplace=True)
    (6): BatchNorm1d(100, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (7): Dropout(p=0.4, inplace=False)
    (8): Linear(in_features=100, out_features=1, bias=True)
  )
)

In [57]:
criterion = nn.MSELoss()
optimizer = torch.optim.Adam(model.parameters(),lr = 0.01)

In [58]:
batch_size = 60000
test_size = int(batch_size*0.2)


In [59]:
# DATA SHUFFLED ALREADY
cat_train = cats[:batch_size-test_size]
cat_test = cats[batch_size-test_size:batch_size]
cont_train = cont[:batch_size-test_size]
cont_test = cont[batch_size-test_size:batch_size]

In [60]:
len(y)


120000

In [61]:
y_train = y[:batch_size-test_size]
y_test = y[batch_size-test_size:batch_size]

In [62]:
import time

start_time = time.time()

epochs = 300

losses = []

for i in range(epochs):
    i += 1
    
    y_pred = model(cat_train,cont_train)
    loss=  torch.sqrt(criterion(y_pred,y_train)) #RMSE
    losses.append(loss)
    
    if i%10==1:
        print(f"epochs is on {i} loss is {loss}")
    
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
        

duration = time.time() - start_time
print(f"Duration is {duration/60}minutes")

epochs is on 1 loss is 12.489313125610352
epochs is on 11 loss is 9.715728759765625
epochs is on 21 loss is 8.062821388244629
epochs is on 31 loss is 4.986583232879639
epochs is on 41 loss is 4.15334415435791
epochs is on 51 loss is 3.591176748275757
epochs is on 61 loss is 3.494988441467285
epochs is on 71 loss is 3.424917459487915
epochs is on 81 loss is 3.355624198913574
epochs is on 91 loss is 3.323641777038574
epochs is on 101 loss is 3.2789673805236816
epochs is on 111 loss is 3.2862839698791504
epochs is on 121 loss is 3.25956392288208
epochs is on 131 loss is 3.2314863204956055
epochs is on 141 loss is 3.2523176670074463
epochs is on 151 loss is 3.254058599472046
epochs is on 161 loss is 3.217198371887207
epochs is on 171 loss is 3.2310798168182373
epochs is on 181 loss is 3.2106711864471436
epochs is on 191 loss is 3.2144763469696045
epochs is on 201 loss is 3.2123312950134277
epochs is on 211 loss is 3.1982851028442383
epochs is on 221 loss is 3.207380771636963
epochs is on 2

In [127]:
cont.shape

torch.Size([120000, 6])

In [129]:
cats.shape

torch.Size([120000, 3])

In [130]:
y.shape

torch.Size([120000, 1])

In [63]:
with torch.no_grad():
    y_v  = model(cat_test,cont_test)
    loss=  torch.sqrt(criterion(y_v,y_test))
    

In [64]:
loss

tensor(3.1488)