In [1]:
import torch
import numpy as np

In [2]:

arr = np.array([1,2,3,4])

In [4]:
arr.dtype

dtype('int32')

In [6]:
torch.tensor(arr)

tensor([1, 2, 3, 4], dtype=torch.int32)

In [7]:
torch.as_tensor(arr)

tensor([1, 2, 3, 4], dtype=torch.int32)

In [9]:
# 1> Creates copy 
#2> Other addreses so if original is changed thn this too change
my_tensor = torch.tensor(arr)
my_other_tensor = torch.from_numpy(arr)

In [11]:
arr[0] = 9999

In [12]:
my_tensor

tensor([1, 2, 3, 4], dtype=torch.int32)

In [13]:
my_other_tensor

tensor([9999,    2,    3,    4], dtype=torch.int32)

In [14]:
# TENSOR vs tensor

In [15]:
my_new_arr = np.arange(1,10)

In [16]:
torch.tensor(my_new_arr)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

In [19]:
torch.Tensor(my_new_arr).dtype # ALIAS FOR FLOAT 32 

torch.float32

# MEMORY ALLOCATION

In [22]:
torch.empty(4,2) # PLACE HOLDER

tensor([[0.0000e+00, 5.9694e-39],
        [1.8754e+28, 1.0153e-08],
        [1.0812e-05, 1.2813e-11],
        [1.6852e+22, 3.3354e-09]])

In [26]:
torch.zeros(4,3) # INFLOAT

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [30]:
torch.zeros(5,3,dtype = torch.int64).dtype

torch.int64

In [33]:
torch.ones(4,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [34]:
torch.arange(0,18,2)

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16])

In [36]:
torch.arange(0,18,2).reshape(3,3)

tensor([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]])

In [38]:
TT = torch.tensor([1,2,3])

In [40]:
TT.dtype

torch.int64

In [41]:
TT = TT.type(torch.int32)

In [42]:
TT.dtype

torch.int32

# Random int

In [43]:
torch.rand(4,3) # FROM UNIFORM DISTRIBUTION

tensor([[0.9244, 0.9674, 0.8216],
        [0.6423, 0.1297, 0.9187],
        [0.6580, 0.0074, 0.2537],
        [0.2730, 0.1959, 0.8090]])

In [46]:
torch.randn(4,3) # std = 1 # Nrmal dist

tensor([[-2.6102, -0.7582,  0.1561],
        [-0.3620,  1.6469, -1.5179],
        [ 0.8443,  0.0503,  0.2584],
        [-0.3686,  0.3019, -0.0784]])

In [50]:
torch.randint(low = 0,high = 11,size =(5,5) ) # Excludes high value

tensor([[ 1,  7,  5,  8,  4],
        [ 6,  0,  0,  4,  0],
        [ 4, 10,  1,  8,  2],
        [ 3,  9,  6,  3,  0],
        [ 7,  6,  1,  8, 10]])

In [51]:
x = torch.zeros(2,5)

In [53]:
x.size()

torch.Size([2, 5])

In [54]:
torch.rand_like(x)

tensor([[0.3209, 0.0142, 0.1424, 0.4487, 0.1320],
        [0.1329, 0.3686, 0.9237, 0.4253, 0.9845]])

In [56]:
torch.randn_like(x)

tensor([[-1.4121, -1.6083, -0.3255,  1.3369,  0.4866],
        [ 1.4752,  0.4441, -0.2597,  0.6363,  0.1218]])

In [57]:
torch.randint_like(x,low = 1 , high = 10)

tensor([[5., 6., 1., 5., 3.],
        [4., 3., 1., 2., 5.]])

In [62]:
torch.manual_seed(42)
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

# TENSOR OPERATIONS

In [65]:
a = torch.arange(6).reshape(3,2)

In [66]:
a

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [68]:
a[:1]

tensor([[0, 1]])

In [71]:
a[:,1] 
#  INDEXING FOR COL

tensor([1, 3, 5])

In [72]:
a[:,1:] # SLICING FOR COL

tensor([[1],
        [3],
        [5]])

In [73]:
x = torch.arange(10)

In [74]:
x.view(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [75]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
x.reshape(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [77]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
z = x.view(2,5)

In [80]:
z

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [82]:
x[0] = 9999

In [83]:
x

tensor([9999,    1,    2,    3,    4,    5,    6,    7,    8,    9])

In [84]:
z

tensor([[9999,    1,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

# INFER SIZE 

In [87]:
x.view(-1,5) # Automatically infer -1 for shape

tensor([[9999,    1,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

In [88]:
x.view(2,-1)

tensor([[9999,    1,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

In [89]:
x.view(5,-1)

tensor([[9999,    1],
        [   2,    3],
        [   4,    5],
        [   6,    7],
        [   8,    9]])

# Mathematical oprt

In [108]:
a = torch.tensor([1,2,3,4])
b = torch.tensor([5,6,7,8])

In [109]:
a+b

tensor([ 6,  8, 10, 12])

In [110]:
torch.add(a,b)

tensor([ 6,  8, 10, 12])

In [111]:
a.mul(b)

tensor([ 5, 12, 21, 32])

In [112]:
# to reassign
a.mul_(b)

tensor([ 5, 12, 21, 32])

In [113]:
a# reassigned

tensor([ 5, 12, 21, 32])

In [114]:
a*b

tensor([ 25,  72, 147, 256])

In [115]:
a.dot(b)

tensor(500)

# ADVANCE OPERATIONS

In [116]:
a=torch.tensor([[1,3],[5,76],[3,4]])
b=torch.tensor([[0,2,3],[1,2,4]])

In [117]:
a.shape

torch.Size([3, 2])

In [118]:
b.shape

torch.Size([2, 3])

In [119]:
torch.mm(a,b)

tensor([[  3,   8,  15],
        [ 76, 162, 319],
        [  4,  14,  25]])

In [120]:
a@b

tensor([[  3,   8,  15],
        [ 76, 162, 319],
        [  4,  14,  25]])

# NORM

In [121]:
x = torch.tensor([1.,2.,3.,4.])

In [122]:
x

tensor([1., 2., 3., 4.])

In [123]:
x.norm()

tensor(5.4772)

In [125]:
x.numel()

4

In [126]:
len(x)

4

In [129]:
a.numel() # only return rows

6

3